### ISSUE TITLE
org.gnome.Platform//3.36 is end-of-life

### ISSUE THREAD

**Issue by vincentmaria** [flathub/fr.free.Homebank#12]
The following message is currently always displayed for Flatpak updates:

> Info: org.gnome.Platform//3.36 is end-of-life, with reason:
>    The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
> Applications using this runtime:
>    fr.free.Homebank

**Comment by alexpattyn** [comment]
Thanks for reporting. Pending https://github.com/flathub/fr.free.Homebank/pull/11 this should be sorted out.

**Comment by arghanath007** [comment]
# Trying to Update my Flatpak apps
```
~ ➤ flatpak update                                                                                                    
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.calo001.fondo
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Nothing to do.
```

> When I was trying to update my flatpak apps, I got this error. I was looking at solutions but everyone was saying to purge the unused apps but I am using those apps though on a regular basis.
