### ISSUE TITLE
Tighten up some permissions

### ISSUE THREAD

**Issue by alexpattyn** [flathub/fr.free.Homebank#14]
Would a PR to remove the following be fine?

- home dir access (replace with xdg-documents along with a note in the READ.ME on how users can add other locations manually)
- network (Doesn't seem to be used for anything by default)
- dri (Doesn't seem necessary seeing as anything <gtk4 isn't gpu accelerated AFAIK)

**Comment by hfiguiere** [comment]
Fixed with #15
