### ISSUE TITLE
how to enable portal file picker?

### ISSUE THREAD

**Issue by boredsquirrel** [flathub/fr.free.Homebank#36]
I tried the env var `GTK_USE_PORTAL=1` but it didnt change anything. Having portals enabled would be helpful.

**Comment by EmmanuelP** [comment]
Use of the portal file chooser must be enabled in the application, by using GtkFileChooserNative: <https://docs.flatpak.org/en/latest/portals.html>. You may request this change on HomeBank issue report system: <https://launchpad.net/homebank/+filebug>

**Comment by boredsquirrel** [comment]
I dont have an Ubuntu Launchpad Account... Another one? Well...
