### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [flathub/fr.free.Homebank#7]
Hi there,
it would be great if the Flathub version of Homebank could get an update, because **5.3.1** is the current version in Flathub, but the latest is **5.4** (see [here](http://homebank.free.fr/en/news.php)).
Regard FestplattenSchnitzel

**Comment by bilelmoussaoui** [comment]
Feel free to send a merge request

**Comment by ajgringo619** [comment]
How do you send a merge request? I would much rather install Homebank via Flatpak then via another PPA.

**Comment by bilelmoussaoui** [comment]
@alexpattyn fixed that:)

**Comment by FestplattenSchnitzel** [comment]
Thank you! :+1:
